export const GET_ALL_TASKS = "GET_ALL_TASKS";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const DELETE_ACTIVE_TASK = "DELETE_ACTIVE_TASK";
export const DELETE_COMPLETE_TASK = "DELETE_COMPLETE_TASK";
export const REACTIVATE_STATE = "REACTIVATE_STATE";
